apiVersion: v1
kind: Service
metadata:
  name: {{ include "rawfile-csi.fullname" . }}-node
  labels:
    {{- include "rawfile-csi.labels" . | nindent 4 }}
    component: node
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "rawfile-csi.selectorLabels" . | nindent 4 }}
    component: node
